baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Example Site"
  subtitle    = ""

  cover       = "uploads/header.jpg"
  description = "My example site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "theantipode"
  fbName = ""
  githubName = "iamtheantipode"

  logo = ""
  orgName = "The Antipode"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  author = "The Antipode"
  authorAvatar = "uploads/profile_picture.jpg"
  authorLocation = "Somewhere, Himalayas"
  authorWebsite = "https://blog.theantipode.org"
  authorDescription = "TBD..."

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Coding"
  url = "/coding"
  weight = 100

[[menu.main]]
  name = "Design"
  url = "/design"
  weight = 99

[[menu.main]]
  name = "Life"
  url = "/life"
  weight = 98